### ISSUE TITLE
Insolation version pinning - is this necessary ? 

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/CalibrateAtmos.jl#69]
Given the new atmosphere component release - can we relax this version requirement?

https://github.com/CliMA/CalibrateAtmos.jl/blob/e16d189eca5668629968a4cc5b12fdb5209793f6/experiments/sphere_held_suarez_rhoe_equilmoist/Project.toml#L16

**Comment by nefrathenrici** [comment]
To remove the compat, I need to update the observational data for the sphere HS experiment to use the newest Atmos release. I will get around to it next week!
